IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMER' AND COLUMN_NAME = 'EmailOTP')
BEGIN
	ALTER TABLE Customer ADD EmailOTP varchar(6)
END

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMER' AND COLUMN_NAME = 'MobileOTP')
BEGIN
	ALTER TABLE Customer ADD MobileOTP varchar(6)
END

IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'CUSTOMER' AND COLUMN_NAME = 'StatusId')
BEGIN
	ALTER TABLE Customer ADD StatusId int
END
GO
