ALTER TABLE [dbo].[BookAdmin] ADD CONSTRAINT
		    [IX_BookAdmin] UNIQUE NONCLUSTERED 
		    (
		    	[BookAccountId] ASC
		    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
Go
