IF EXISTS (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'Z-PurchaseBillMaster-Z' AND CONSTRAINT_NAME = 'IX_PurchaseBillMaster_Firm')
BEGIN 
ALTER TABLE [dbo].[Z-PurchaseBillMaster-Z] DROP CONSTRAINT [IX_PurchaseBillMaster_Firm];
END 
GO

IF EXISTS (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'Z-PurchaseBillMaster-Z' AND CONSTRAINT_NAME = 'IX_PurchaseBillMaster_Branch')
BEGIN 
ALTER TABLE [dbo].[Z-PurchaseBillMaster-Z] DROP CONSTRAINT [IX_PurchaseBillMaster_Branch];
END 
GO

IF NOT EXISTS (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'Z-PurchaseBillMaster-Z' AND CONSTRAINT_NAME = 'IX_PurchaseBillMaster_Firm')
BEGIN 
ALTER TABLE [dbo].[Z-PurchaseBillMaster-Z] ADD CONSTRAINT
		    [IX_PurchaseBillMaster_Firm] UNIQUE NONCLUSTERED 
		    (
		    	[FirmId] ASC,
		    	[YearId] ASC,
		    	[BookBranchMappingId] ASC,
		    	[EntryTypeId] ASC,
		    	[BillNumberFirm] ASC
		    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'Z-PurchaseBillMaster-Z' AND CONSTRAINT_NAME = 'IX_PurchaseBillMaster_Branch')
BEGIN 
ALTER TABLE [dbo].[Z-PurchaseBillMaster-Z] ADD CONSTRAINT
		    [IX_PurchaseBillMaster_Branch] UNIQUE NONCLUSTERED 
		    (
		    	[BranchId] ASC,
		    	[YearId] ASC,
		    	[BookBranchMappingId] ASC,
		    	[EntryTypeId] ASC,
		    	[BillNumberBranch] ASC
		    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
GO