IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'Z-SalesBillMaster-Z' AND CONSTRAINT_NAME = 'IX_SalesBillMaster_Firm')
BEGIN 
ALTER TABLE [dbo].[Z-SalesBillMaster-Z] DROP CONSTRAINT [IX_SalesBillMaster_Firm];
END 
GO

IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'Z-SalesBillMaster-Z' AND CONSTRAINT_NAME = 'IX_SalesBillMaster_Branch')
BEGIN 
ALTER TABLE [dbo].[Z-SalesBillMaster-Z] DROP CONSTRAINT [IX_SalesBillMaster_Branch];
END 
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'Z-SalesBillMaster-Z' AND CONSTRAINT_NAME = 'IX_SalesBillMaster_Firm')
BEGIN 
ALTER TABLE [dbo].[Z-SalesBillMaster-Z] ADD CONSTRAINT
		    [IX_SalesBillMaster_Firm] UNIQUE NONCLUSTERED 
		    (
		    	[FirmId] ASC,
		    	[YearId] ASC,
		    	[BookBranchMappingId] ASC,
		    	[EntryTypeId] ASC,
		    	[BillNumber] ASC
		    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_NAME = 'Z-SalesBillMaster-Z' AND CONSTRAINT_NAME = 'IX_SalesBillMaster_Branch')
BEGIN 
ALTER TABLE [dbo].[Z-SalesBillMaster-Z] ADD CONSTRAINT
		    [IX_SalesBillMaster_Branch] UNIQUE NONCLUSTERED 
		    (
		    	[BranchId] ASC,
		    	[YearId] ASC,
		    	[BookBranchMappingId] ASC,
		    	[EntryTypeId] ASC,
		    	[SerialNumberOfBranch] ASC
		    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END
GO