using System.ComponentModel;

namespace Adroit.Accounting.Model.PrintVariables
{
    public enum LRPrintVariables
    {
        [Description("[NO_OF_ARTICLES]")]
        NO_OF_ARTICLES,
        [Description("[AT_OWNER_RISK]")]
        NOTES,
        [Description("[SUBJECT_TO]")]
        TERMS_AND_CONDITIONS,
        [Description("[COMPANY_NAME]")]
        FIRM_NAME,
        [Description("[FIRM_GST_TYPE]")]
        FIRM_GST_TYPE,
        [Description("[FIRM_TYPE]")]
        FIRM_TYPE,
        [Description("[FIRM_OWNER]")]
        FIRM_OWNER,
        [Description("[FIRM_AADHAR_UID]")]
        FIRM_AADHAR_UID,
        [Description("[FIRM_TAN]")]
        FIRM_TAN,
        [Description("[FIRM_IEC]")]
        FIRM_IEC,
        [Description("[FIRM_LUT_BOND]")]
        FIRM_LUT_BOND,
        [Description("[FIRM_BUSINESS]")]
        FIRM_BUSINESS,
        [Description("[BRANCH_NAME]")]
        BRANCH_NAME,
        [Description("[BRANCH_TYPE]")]
        BRANCH_TYPE,
        [Description("[BRANCH_PRINT_TITLE]")]
        BRANCH_PRINT_TITLE,
        [Description("[BRANCH_CODE]")]
        BRANCH_CODE,
        [Description("[TRA_GST_NO]")]
        BRANCH_GST_NO,
        [Description("[BRANCH_PAN_NO]")]
        BRANCH_PAN_NO,
        [Description("[ADDRESS]")]
        BRANCH_ADDRESS,
        [Description("[BRANCH_CITY]")]
        BRANCH_CITY,
        [Description("[BRANCH_TALUKA]")]
        BRANCH_TALUKA,
        [Description("[BRANCH_DISTRICT]")]
        BRANCH_DISTRICT,
        [Description("[BRANCH_STATE]")]
        BRANCH_STATE,
        [Description("[PHONE_NUMBER]")]
        BRANCH_PHONE_NO,
        [Description("[BRANCH_MOBILE_NO]")]
        BRANCH_MOBILE_NO,
        [Description("[BRANCH_ALTERNATE_MOBILE_NO]")]
        BRANCH_ALTERNATE_MOBILE_NO,
        [Description("[COMPAYE_EMAIL]")]
        BRANCH_EMAIL_ADDRESS,
        [Description("[L_R_NO]")]
        LR_NUMBER,
        [Description("[DATE]")]
        LR_DATE,
        [Description("[FROM_CITY]")]
        BOOKING_CITY,
        [Description("[TO_CITY]")]
        DELIVERY_CITY,
        [Description("[CONSIGNEE_TO]")]
        CONSIGNEE_NAME,
        [Description("[TO_GSTIN]")]
        CONSIGNEE_GST,
        [Description("[CONSIGNEE_MOBILE]")]
        CONSIGNEE_MOBILE,
        [Description("[CONSIGNOR_FROM]")]
        CONSIGNOR_NAME,
        [Description("[FROM_GSTIN]")]
        CONSIGNOR_GST,
        [Description("[CONSIGNOR_MOBILE]")]
        CONSIGNOR_MOBILE,
        [Description("[PAYMENT_TYPE]")]
        PAY_TYPE,
        [Description("[PARCLE]")]
        PARCLE,
        [Description("[DESCRIPTION]")]
        DESCRIPTION,
        [Description("[PACKING]")]
        PACKING,
        [Description("[ACT_WT]")]
        ACTUAL_WEIGHT,
        [Description("[CH_WT]")]
        CHARGE_WEIGHT,
        [Description("[RATE_ON]")]
        RATE_ON,
        [Description("[RATE]")]
        RATE,
        [Description("[FREIGHT]")]
        FREIGHT,
        [Description("[AMOUNT]")]
        AMOUNT,
        [Description("[CHARGE_LABEL_1]")]
        CHARGE_LABEL_1,
        [Description("[CHARGE_LABEL_1_VAL]")]
        CHARGE_LABEL_1_VAL,
        [Description("[CHARGE_LABEL_2]")]
        CHARGE_LABEL_2,
        [Description("[CHARGE_LABEL_2_VAL]")]
        CHARGE_LABEL_2_VAL,
        [Description("[CHARGE_LABEL_3]")]
        CHARGE_LABEL_3,
        [Description("[CHARGE_LABEL_3_VAL]")]
        CHARGE_LABEL_3_VAL,
        [Description("[CHARGE_LABEL_4]")]
        CHARGE_LABEL_4,
        [Description("[CHARGE_LABEL_4_VAL]")]
        CHARGE_LABEL_4_VAL,
        [Description("[CHARGE_LABEL_5]")]
        CHARGE_LABEL_5,
        [Description("[CHARGE_LABEL_5_VAL]")]
        CHARGE_LABEL_5_VAL,
        [Description("[CHARGE_LABEL_6]")]
        CHARGE_LABEL_6,
        [Description("[CHARGE_LABEL_6_VAL]")]
        CHARGE_LABEL_6_VAL,
        [Description("[BILL_AMOUNT]")]
        NET_AMOUNT,
        [Description("[IN_WORDS]")]
        IN_WORDS,
        [Description("[INVOICE_NO]")]
        INVOICE_NUMBER,
        [Description("[INVOICE_VALUE]")]
        INVOICE_VALUE,
        [Description("[EWAY_BILL_NO]")]
        EWAY_BILL_NUMBER,
        [Description("[PRIVATE_MARK]")]
        PRIVATE_MARK,
        [Description("[VEHICLE_NO]")]
        VEHICLE_NUMBER,
        [Description("[DELIVERY_AT]")]
        DELIVERY_AT,
        [Description("[DELIVERY_TYPE]")]
        DELIVERY_TYPE,
        [Description("[REMARKS]")]
        REMARKS,
        [Description("[GST_P]")]
        GST_P,
        [Description("[PRODUCT_NAME]")]
        PRODUCT_NAME,
        [Description("[BOOK_NAME]")]
        BOOK_NAME
    }
}
