CREATE OR ALTER PROCEDURE [dbo].[sp_BoxSettingsSave]
(
    @Id int,
    @SoftwareId tinyint,
    @CustomerId int,
    @CusomerFirmId int,
    @Product_ProductName	bit,
	@Product_ProductName2	bit,
	@Product_ProductName3	bit,
	@Product_CodeSKU	bit,
	@Product_Design	bit,
	@Product_Colour	bit,
	@Product_Size	bit,
	@Product_Fabric	bit,
	@Product_MRP	bit,
	@Product_DistributorRate	bit,
	@Product_DealerRate	bit,
	@Product_AvgPack	bit,
	@Product_BoxPack	bit,
	@Product_ProductPacking	bit,
	@Product_CentralCess	bit,
	@Product_StateCess	bit,
	@Product_Group	bit,
	@Product_SubGroup	bit,
	@Product_Discount	bit,
	@Product_FIFORate	bit,
	@Product_OpStockQty	bit,
	@Product_PurchaseRate	bit,
	@Product_CalculationOn	bit,
	@Product_Cut	bit,
	@Product_RolMin	bit,
	@Product_RolMax	bit,
	@Product_OpStockNos	bit,
	@Product_LooseQty	bit,
	@Product_PurchaseRateUpdate	bit,
	@Product_QualityType	bit,
	@Product_YarnDenierWt	bit,
	@Product_RateMeter	bit,
	@Product_YarnShadeNo	bit,
	@Account_Taluka	bit,
	@Account_District	bit,
	@Account_Country	bit,
	@Account_Area	bit,
	@Account_TransporterName	bit,
	@Account_TransporterGSTNo	bit,
	@Account_VehicleNumber	bit,
	@Account_Broker	bit,
	@Account_DeliveryParty	bit,
	@Account_HasteParty	bit,
	@Account_ShippingParty	bit,
	@GeneralExpenseMulti_Group	bit,
	@GeneralExpenseMulti_Discount	bit,
	@GeneralExpenseMulti_OtherCharges	bit,
	@GeneralExpenseMulti_Group2	bit,
	@GeneralExpenseMulti_Discount2	bit,
	@GeneralExpenseMulti_OtherCharges2	bit,
	@GeneralExpenseMulti_TDS	bit,
	@GeneralExpenseMulti_SGST	bit,
	@GeneralExpenseMulti_CGST	bit,
	@GeneralExpenseMulti_IGST	bit,
	@GeneralExpenseMulti_StateCess	bit,
	@GeneralExpenseMulti_CentralCess	bit,
	@GeneralExpenseMulti_TCS	bit,
    @UserId int,
    @Active bit
)
AS
BEGIN
    BEGIN TRAN
    BEGIN TRY
        IF EXISTS (SELECT Id FROM BoxSetting WHERE Id = @Id)
        BEGIN
            UPDATE BoxSetting SET
				Product_ProductName = @Product_ProductName,
				Product_ProductName2 = @Product_ProductName2,
				Product_ProductName3 = @Product_ProductName3,
				Product_CodeSKU = @Product_CodeSKU,
				Product_Design = @Product_Design,
				Product_Colour = @Product_Colour,
				Product_Size = @Product_Size,
				Product_Fabric = @Product_Fabric,
				Product_MRP = @Product_MRP,
				Product_DistributorRate = @Product_DistributorRate,
				Product_DealerRate = @Product_DealerRate,
				Product_AvgPack = @Product_AvgPack,
				Product_BoxPack = @Product_BoxPack,
				Product_ProductPacking = @Product_ProductPacking,
				Product_CentralCess = @Product_CentralCess,
				Product_StateCess = @Product_StateCess,
				Product_Group = @Product_Group,
				Product_SubGroup = @Product_SubGroup,
				Product_Discount = @Product_Discount,
				Product_FIFORate = @Product_FIFORate,
				Product_OpStockQty = @Product_OpStockQty,
				Product_PurchaseRate = @Product_PurchaseRate,
				Product_CalculationOn = @Product_CalculationOn,
				Product_Cut = @Product_Cut,
				Product_RolMin = @Product_RolMin,
				Product_RolMax = @Product_RolMax,
				Product_OpStockNos = @Product_OpStockNos,
				Product_LooseQty = @Product_LooseQty,
				Product_PurchaseRateUpdate = @Product_PurchaseRateUpdate,
				Product_QualityType = @Product_QualityType,
				Product_YarnDenierWt = @Product_YarnDenierWt,
				Product_RateMeter = @Product_RateMeter,
				Product_YarnShadeNo = @Product_YarnShadeNo,
				Account_Taluka = @Account_Taluka,
				Account_District = @Account_District,
				Account_Country = @Account_Country,
				Account_Area = @Account_Area,
				Account_TransporterName = @Account_TransporterName,
				Account_TransporterGSTNo = @Account_TransporterGSTNo,
				Account_VehicleNumber = @Account_VehicleNumber,
				Account_Broker = @Account_Broker,
				Account_DeliveryParty = @Account_DeliveryParty,
				Account_HasteParty = @Account_HasteParty,
				Account_ShippingParty = @Account_ShippingParty,
				GeneralExpenseMulti_Group = @GeneralExpenseMulti_Group,
				GeneralExpenseMulti_Discount = @GeneralExpenseMulti_Discount,
				GeneralExpenseMulti_OtherCharges = @GeneralExpenseMulti_OtherCharges,
				GeneralExpenseMulti_Group2 = @GeneralExpenseMulti_Group2,
				GeneralExpenseMulti_Discount2 = @GeneralExpenseMulti_Discount2,
				GeneralExpenseMulti_OtherCharges2 = @GeneralExpenseMulti_OtherCharges2,
				GeneralExpenseMulti_TDS = @GeneralExpenseMulti_TDS,
				GeneralExpenseMulti_SGST = @GeneralExpenseMulti_SGST,
				GeneralExpenseMulti_CGST = @GeneralExpenseMulti_CGST,
				GeneralExpenseMulti_IGST = @GeneralExpenseMulti_IGST,
				GeneralExpenseMulti_StateCess = @GeneralExpenseMulti_StateCess,
				GeneralExpenseMulti_CentralCess = @GeneralExpenseMulti_CentralCess,
				GeneralExpenseMulti_TCS = @GeneralExpenseMulti_TCS,
                Active = @Active,
                ModifiedById = @UserId, 
                ModifiedOn = GETUTCDate()
            WHERE Id = @Id 
        END
        ELSE 
        BEGIN
            INSERT INTO BoxSetting (SoftwareId, CustomerId, CusomerFirmId,  
					Product_ProductName,
					Product_ProductName2,
					Product_ProductName3,
					Product_CodeSKU,
					Product_Design,
					Product_Colour,
					Product_Size,
					Product_Fabric,
					Product_MRP,
					Product_DistributorRate,
					Product_DealerRate,
					Product_AvgPack,
					Product_BoxPack,
					Product_ProductPacking,
					Product_CentralCess,
					Product_StateCess,
					Product_Group,
					Product_SubGroup,
					Product_Discount,
					Product_FIFORate,
					Product_OpStockQty,
					Product_PurchaseRate,
					Product_CalculationOn,
					Product_Cut,
					Product_RolMin,
					Product_RolMax,
					Product_OpStockNos,
					Product_LooseQty,
					Product_PurchaseRateUpdate,
					Product_QualityType,
					Product_YarnDenierWt,
					Product_RateMeter,
					Product_YarnShadeNo,
					Account_Taluka,
					Account_District,
					Account_Country,
					Account_Area,
					Account_TransporterName,
					Account_TransporterGSTNo,
					Account_VehicleNumber,
					Account_Broker,
					Account_DeliveryParty,
					Account_HasteParty,
					Account_ShippingParty,
					GeneralExpenseMulti_Group,
					GeneralExpenseMulti_Discount,
					GeneralExpenseMulti_OtherCharges,
					GeneralExpenseMulti_Group2,
					GeneralExpenseMulti_Discount2,
					GeneralExpenseMulti_OtherCharges2,
					GeneralExpenseMulti_TDS,
					GeneralExpenseMulti_SGST,
					GeneralExpenseMulti_CGST,
					GeneralExpenseMulti_IGST,
					GeneralExpenseMulti_StateCess,
					GeneralExpenseMulti_CentralCess,
					GeneralExpenseMulti_TCS,
                    AddedOn, AddedById, Active)
                VALUES (@SoftwareId, @CustomerId, @CusomerFirmId, 
					@Product_ProductName,
					@Product_ProductName2,
					@Product_ProductName3,
					@Product_CodeSKU,
					@Product_Design,
					@Product_Colour,
					@Product_Size,
					@Product_Fabric,
					@Product_MRP,
					@Product_DistributorRate,
					@Product_DealerRate,
					@Product_AvgPack,
					@Product_BoxPack,
					@Product_ProductPacking,
					@Product_CentralCess,
					@Product_StateCess,
					@Product_Group,
					@Product_SubGroup,
					@Product_Discount,
					@Product_FIFORate,
					@Product_OpStockQty,
					@Product_PurchaseRate,
					@Product_CalculationOn,
					@Product_Cut,
					@Product_RolMin,
					@Product_RolMax,
					@Product_OpStockNos,
					@Product_LooseQty,
					@Product_PurchaseRateUpdate,
					@Product_QualityType,
					@Product_YarnDenierWt,
					@Product_RateMeter,
					@Product_YarnShadeNo,
					@Account_Taluka,
					@Account_District,
					@Account_Country,
					@Account_Area,
					@Account_TransporterName,
					@Account_TransporterGSTNo,
					@Account_VehicleNumber,
					@Account_Broker,
					@Account_DeliveryParty,
					@Account_HasteParty,
					@Account_ShippingParty,
					@GeneralExpenseMulti_Group,
					@GeneralExpenseMulti_Discount,
					@GeneralExpenseMulti_OtherCharges,
					@GeneralExpenseMulti_Group2,
					@GeneralExpenseMulti_Discount2,
					@GeneralExpenseMulti_OtherCharges2,
					@GeneralExpenseMulti_TDS,
					@GeneralExpenseMulti_SGST,
					@GeneralExpenseMulti_CGST,
					@GeneralExpenseMulti_IGST,
					@GeneralExpenseMulti_StateCess,
					@GeneralExpenseMulti_CentralCess,
					@GeneralExpenseMulti_TCS,
                    GETUTCDATE(), @UserId, @Active)
            
            SET @Id = SCOPE_IDENTITY()
        END
        
        COMMIT TRAN

        SELECT @Id
    END TRY
    BEGIN CATCH
        DECLARE @error INT, @message VARCHAR(4000), @xstate INT;
        SELECT @error = ERROR_NUMBER(), @message = ERROR_MESSAGE(), @xstate = XACT_STATE();
        ROLLBACK TRAN

        IF (CHARINDEX('IX_BoxSetting', @message) > 0)
		BEGIN
			SET @message = 'Box setting already exist!'
		END

        RAISERROR ('%s', 16, 1, @message);
    END CATCH
END
GO