CREATE OR ALTER PROCEDURE [dbo].[sp_MenuSettingsSave]
(
    @Id int,
    @SoftwareId tinyint,
    @SoftwarePlanId tinyint,
    @CustomerId int,
    @CusomerFirmId int,
    @CustomerFirmBranchId int,
    @CustomerUserId int,
    @Master__Adroit__Software__Software_Master bit,
    @Master__Adroit__Software__Plan bit,
    @Master__Adroit__Software__Businesses bit,
    @Master__Adroit__Customer__Customers bit,
    @Master__Adroit__Customer__Branch_Types bit,
    @Master__Adroit__Customer__Menu_Setting bit,
    @Master__Adroit__Customer__Box_Setting bit,
    @Master__Adroit__Account__Accounts bit,
    @Master__Adroit__Account__Secondary_Account_Group bit,
    @Master__Adroit__Account__Primary_Account_Group bit,
    @Master__Adroit__Account__Books bit,
    @Master__Adroit__Account__Book_Types bit,
    @Master__Adroit__Account__Bill_From bit,
    @Master__Adroit__Account__Book_Settings bit,
    @Master__Adroit__Location__City bit,
    @Master__Adroit__Location__Taluka bit,
    @Master__Adroit__Location__District bit,
    @Master__Adroit__Location__State bit,
    @Master__Adroit__Location__Country bit,
    @Master__Adroit__GST__Rate bit,
    @Master__Adroit__GST__Invoice_Types bit,
    @Master__Adroit__GST__Ports bit,
    @Master__Adroit__GST__Collections bit,
    @Master__Adroit__Product__Colour bit,
    @Master__Adroit__Product__Amount_Calculations bit,
    @Master__Adroit__Product__Size bit,
    @Master__Adroit__Product__Stock_Types bit,
    @Master__Adroit__Product__Quality_Types bit,
    @Master__Adroit__Transport__Packing bit,
    @Master__Adroit__Transport__Description bit,
    @Master__Adroit__Transport__LR_Charges bit,
    @Master__Customer__Firms bit,
    @Master__Customer__Branches bit,
    @Master__Customer__Users bit,
    @Master__Account__Add bit,
    @Master__Account__Secondary_Account_Group bit,
    @Master__Account__Primary_Account_Group bit,
    @Master__Product__Add bit,
    @Master__Product__Design bit,
    @Master__Product__Colour bit,
    @Master__Product__Size bit,
    @Master__Product__Fabric bit,
    @Master__Product__Group bit,
    @Master__Product__Sub_Group bit,
    @Master__Product__Shade bit,
    @Master__Product__Packing bit,
    @Master__Broker bit,
    @Master__Machine bit,
    @Master__Yarn_Shade bit,
    @Master__Yarn_Recipes bit,
    @Master__Process bit,
    @Master__Cataloge bit,
    @Master__Employee bit,
    @Master__Location__City bit,
    @Master__Location__Branch_City_Mapping bit,
    @Master__Vehicles bit,
    @Master__Drivers bit,
    @Master__LR__Packing bit,
    @Master__LR__Description bit,
    @Transaction__Booking__LR bit,
    @Transaction__Booking__Chalan bit,
    @Transaction__Booking__Invoice bit,
    @Transaction__Delivery__Chalan_Receive bit,
    @Transaction__Delivery__Delivery_Invoice bit,
    @Transaction__Sales__Quotation bit,
    @Transaction__Sales__Praforma_Invoice bit,
    @Transaction__Sales__Sales_Order bit,
    @Transaction__Sales__Chalan_Packing_Slip bit,
    @Transaction__Sales__Sales bit,
    @Transaction__Sales__Sales_Return bit,
    @Transaction__Purchase__Purchase_Order bit,
    @Transaction__Purchase__Purchase_Chalan bit,
    @Transaction__Purchase__Purchase bit,
    @Transaction__Purchase__Jobwork_Purchase bit,
    @Transaction__Purchase__Purchase_Return bit,
    @Transaction__Purchase__General_Expenses bit,
    @Transaction__Purchase__General_Expenses_Multi bit,
    @Transaction__Credit_Note bit,
    @Transaction__Debit_Note bit,
    @Account__Payment__Bank_Payment bit,
    @Account__Payment__Cash_Payment bit,
    @Account__Receive__Bank_Receive bit,
    @Account__Receive__Cash_Receive bit,
    @Account__Account_Opening_Balance bit,
    @Account__Product_Opening_Stock bit,
    @Account__Journal_JV__General_JV bit,
    @Account__Journal_JV__Bill_Base_JV bit,
    @Account__GST_Filling__GSTR_01 bit,
    @Account__GST_Filling__GSTR_02_2A_2B bit,
    @Account__GST_Filling__GSTR_03B bit,
    @Account__GST_Filling__GSTR_04_4B bit,
    @Account__GST_Filling__GSTR_09_9C bit,
    @Account__GST_Filling__ITC_04 bit,
    @Account__Reconsilation bit,
    @Account__Cash_Auto_Payment bit,
    @Reports__SalesAndPurchase__Sales__Detail_Register bit,
    @Reports__SalesAndPurchase__Sales__Summary_Register bit,
    @Reports__SalesAndPurchase__Sales__Item_Wise_Register bit,
    @Reports__SalesAndPurchase__Sales__Monthly_Register bit,
    @Reports__SalesAndPurchase__Sales__Chalan_Regsiter bit,
    @Reports__SalesAndPurchase__Sales__Sales_Order_Regsiter bit,
    @Reports__SalesAndPurchase__Sales__Sales_Quotation_Register bit,
    @Reports__SalesAndPurchase__Sales__Proforma_Invoice_Register bit,
    @Reports__SalesAndPurchase__Purchase__Detail_Register bit,
    @Reports__SalesAndPurchase__Purchase__Summary_Register bit,
    @Reports__SalesAndPurchase__Purchase__Item_Wise_Register bit,
    @Reports__SalesAndPurchase__Purchase__Monthly_Register bit,
    @Reports__SalesAndPurchase__Purchase__Chalan_Regsiter bit,
    @Reports__SalesAndPurchase__Purchase__Purchase_Order_Regsiter bit,
    @Reports__SalesAndPurchase__Outstanding__Sales bit,
    @Reports__SalesAndPurchase__Outstanding__Sales_Vs_Ledger bit,
    @Reports__SalesAndPurchase__Outstanding__Purchase bit,
    @Reports__SalesAndPurchase__Outstanding__Purchase_Vs_Ledger bit,
    @Reports__SalesAndPurchase__Outstanding__Aiging_Register bit,
    @Reports__SalesAndPurchase__Outstanding__Interest_Calculator bit,
    @Reports__BookAndRegister__LR_Booking_Register__LR_Register bit,
    @Reports__BookAndRegister__LR_Booking_Register__Stock_Register bit,
    @Reports__BookAndRegister__LR_Booking_Register__Booking_Register bit,
    @Reports__BookAndRegister__LR_Booking_Register__Daily_Summary bit,
    @Reports__BookAndRegister__LR_Booking_Register__Monthly_Summary bit,
    @Reports__BookAndRegister__LR_Booking_Register__Chalan_Loading_Report bit,
    @Reports__BookAndRegister__LR_Booking_Register__Chalan_Monthly_Report bit,
    @Reports__BookAndRegister__LR_Delivery_Register__LR_Register bit,
    @Reports__BookAndRegister__LR_Delivery_Register__Stock_Register bit,
    @Reports__BookAndRegister__LR_Delivery_Register__Delivery_Register bit,
    @Reports__BookAndRegister__LR_Delivery_Register__Daily_Summary bit,
    @Reports__BookAndRegister__LR_Delivery_Register__Monthly_Summary bit,
    @Reports__BookAndRegister__LR_Delivery_Register__Chalan_Loading_Report bit,
    @Reports__BookAndRegister__LR_Delivery_Register__Chalan_Monthly_Report bit,
    @Reports__BookAndRegister__Bank_Book bit,
    @Reports__BookAndRegister__Cash_Book bit,
    @Reports__BookAndRegister__Journal_Book bit,
    @Reports__BookAndRegister__Day_Book bit,
    @Reports__BookAndRegister__Voucher_Book bit,
    @Reports__BookAndRegister__TDSAndTCS_Register bit,
    @Reports__BookAndRegister__Credit_Debit_Note_Register bit,
    @Reports__BookAndRegister__Payroll_Register bit,
    @Reports__BookAndRegister__Brokrage_Register bit,
    @Reports__Stock__Stock_In_Out_Detail bit,
    @Reports__Stock__Stock_Statement bit,
    @Reports__Stock__Item_Wise bit,
    @Reports__Stock__Group_Wise bit,
    @Reports__Stock__Stock_In_Process bit,
    @Reports__Stock__Stock_In_Ware_House bit,
    @Reports__ProdAndInventory__Prod_Register__Yarn bit,
    @Reports__ProdAndInventory__Prod_Register__Beam bit,
    @Reports__ProdAndInventory__Prod_Register__Grey bit,
    @Reports__ProdAndInventory__Prod_Register__General bit,
    @Reports__ProdAndInventory__Batch_Master_Register bit,
    @Reports__ProdAndInventory__Issue_Register bit,
    @Reports__ProdAndInventory__Receive_Register bit,
    @Reports__Jobwork__Work_Issue_Chalan_Reg bit,
    @Reports__Jobwork__Work_Receive_Chalan_Reg bit,
    @Reports__Jobwork__Work_Pending_Reg bit,
    @Reports__Jobwork__Jobwork_Receive_Chalan_Reg bit,
    @Reports__Jobwork__Jobwork_Issue_Chalan_Reg bit,
    @Reports__Jobwork__Jobwork_Pending_Reg bit,
    @Reports__Jobwork__Mill_Issue_Chalan_Reg bit,
    @Reports__Jobwork__Mill_Receive_Chalan_Reg bit,
    @Reports__Jobwork__Mill_Pending_Reg bit,
    @Reports__GST_Register__GSTR_01 bit,
    @Reports__GST_Register__GSTR_02_2A_2B bit,
    @Reports__GST_Register__GSTR_03B bit,
    @Reports__GST_Register__GSTR_04_4B bit,
    @Reports__GST_Register__GSTR_09_9C bit,
    @Reports__GST_Register__ITC_04 bit,
    @Reports__GST_Register__GSTR_SetOff bit,
    @Reports__GST_Register__GSTR_Reconsilation bit,
    @Reports__Account_Register__Ledger_Head_Print bit,
    @Reports__Account_Register__Leadger bit,
    @Reports__Account_Register__Ledger_Multi bit,
    @Reports__Account_Register__Ledger_Month_Wise bit,
    @Reports__Account_Register__Interest_Calculator bit,
    @Reports__Account_Register__Payable_Receivable bit,
    @Reports__Financial_Reports__Trial_Balance_Summary bit,
    @Reports__Financial_Reports__Trial_Balance_Detail bit,
    @Reports__Financial_Reports__Trading_Account bit,
    @Reports__Financial_Reports__ProfitAndLoss bit,
    @Reports__Financial_Reports__Balance_Sheet bit,
    @Reports__Financial_Reports__Balance_Sheet_Schedule bit,
    @Inventory__Production__Consumption_BOM__Batch_Master bit,
    @Inventory__Production__Consumption_BOM__Yarn_Master bit,
    @Inventory__Production__Consumption_BOM__Grey_Master bit,
    @Inventory__Production__Consumption_BOM__Saree_Master bit,
    @Inventory__Production__Gen_Prod__Production bit,
    @Inventory__Production__Gen_Prod__Yarn_Production bit,
    @Inventory__Production__Gen_Prod__Beam_Production bit,
    @Inventory__Production__Gen_Prod__Grey_Production bit,
    @Inventory__Production__Gen_Prod__Saree_Production bit,
    @Inventory__IssueAndReceive__Yarn__Issue bit,
    @Inventory__IssueAndReceive__Yarn__Receive bit,
    @Inventory__IssueAndReceive__Beam__Issue_for_OutsideWork bit,
    @Inventory__IssueAndReceive__Beam__Receive_From_Yarn_Issue bit,
    @Inventory__IssueAndReceive__Grey__Issue_for_OutsideWork bit,
    @Inventory__IssueAndReceive__Grey__Receive_From_OutsideWork bit,
    @Inventory__Beam_Entry bit,
    @Inventory__Inventory__Issue bit,
    @Inventory__Inventory__Receive bit,
    @Inventory__Jobwork__Work_Dispach bit,
    @Inventory__Jobwork__Work_Receive bit,
    @Inventory__Jobwork__Job_Receive bit,
    @Inventory__Jobwork__Job_Issue bit,
    @Inventory__Mill_Jobwork__Issue bit,
    @Inventory__Mill_Jobwork__Receive bit,
    @Inventory__Mill_Jobwork__Job_Receive bit,
    @Inventory__Mill_Jobwork__Job_Issue bit,
    @Inventory__Cutting_Process__Taka_to_Pcs bit,
    @SettingsAndUtilities__Book_Setting__Books bit,
    @SettingsAndUtilities__Book_Setting__Multi_Print_Invoice bit,
    @SettingsAndUtilities__Book_Setting__Multi_Print_Vocher bit,
    @SettingsAndUtilities__Merge__Account_Master bit,
    @SettingsAndUtilities__Merge__Product_Master bit,
    @SettingsAndUtilities__Merge__Broker_Master bit,
    @SettingsAndUtilities__Merge__City_Master bit,
    @SettingsAndUtilities__Merge__Vehicle_Master bit,
    @SettingsAndUtilities__Merge__Driver_Master bit,
    @SettingsAndUtilities__Merge__Packing_Master bit,
    @SettingsAndUtilities__Merge__Description_Master bit,
    @SettingsAndUtilities__Merge__Taka_Merge bit,
    @SettingsAndUtilities__Merge__Taka_Demerge bit,
    @SettingsAndUtilities__Year__Create_New_Year bit,
    @SettingsAndUtilities__Year__Year_End_Process bit,
    @SettingsAndUtilities__Transfer_Next_Year__Closing_Stock bit,
    @SettingsAndUtilities__Transfer_Next_Year__Closing_Amount bit,
    @SettingsAndUtilities__Transfer_Next_Year__Sales_Invoice bit,
    @SettingsAndUtilities__Transfer_Next_Year__Purchase_Invoice bit,
    @SettingsAndUtilities__Transfer_Next_Year__Work_Dispach_For_Job bit,
    @SettingsAndUtilities__Transfer_Next_Year__Job_Receive_For_Work bit,
    @SettingsAndUtilities__Transfer_Next_Year__Mill_Issue bit,
    @SettingsAndUtilities__Transfer_Next_Year__Mill_Job_Receive bit,
    @SettingsAndUtilities__Transfer_Next_Year__Taka_Production bit,
    @SettingsAndUtilities__Transfer_Next_Year__Box_Production bit,
    @SettingsAndUtilities__Delete_Previous_Year__Closing_Stock bit,
    @SettingsAndUtilities__Delete_Previous_Year__Closing_Amount bit,
    @SettingsAndUtilities__Delete_Previous_Year__Sales_Invoice bit,
    @SettingsAndUtilities__Delete_Previous_Year__Purchase_Invoice bit,
    @SettingsAndUtilities__Delete_Previous_Year__Work_Dispach_For_Job bit,
    @SettingsAndUtilities__Delete_Previous_Year__Job_Receive_For_Work bit,
    @SettingsAndUtilities__Delete_Previous_Year__Mill_Issue bit,
    @SettingsAndUtilities__Delete_Previous_Year__Mill_Job_Receive bit,
    @SettingsAndUtilities__Delete_Previous_Year__Taka_Production bit,
    @SettingsAndUtilities__Delete_Previous_Year__Box_Production bit,
    @SettingsAndUtilities__Transport_Setting__Firm bit,
    @SettingsAndUtilities__Transport_Setting__Branch bit,
    @SettingsAndUtilities__Transport_Setting__LR_Rate bit,
    @SettingsAndUtilities__Transport_Setting__Contract_Rate bit,
    @SettingsAndUtilities__Transport_Setting__LR_Booking_Range bit,
    @UserId int
)
AS
BEGIN
    BEGIN TRAN
    BEGIN TRY
        IF EXISTS (SELECT Id FROM MenuSetting WHERE Id = @Id)
        BEGIN
            UPDATE MenuSetting SET
                Master__Adroit__Software__Software_Master = @Master__Adroit__Software__Software_Master,
                Master__Adroit__Software__Plan = @Master__Adroit__Software__Plan,
                Master__Adroit__Software__Businesses = @Master__Adroit__Software__Businesses,
                Master__Adroit__Customer__Customers = @Master__Adroit__Customer__Customers,
                Master__Adroit__Customer__Branch_Types = @Master__Adroit__Customer__Branch_Types,
                Master__Adroit__Customer__Menu_Setting = @Master__Adroit__Customer__Menu_Setting,
                Master__Adroit__Customer__Box_Setting = @Master__Adroit__Customer__Box_Setting,
                Master__Adroit__Account__Accounts = @Master__Adroit__Account__Accounts,
                Master__Adroit__Account__Secondary_Account_Group = @Master__Adroit__Account__Secondary_Account_Group,
                Master__Adroit__Account__Primary_Account_Group = @Master__Adroit__Account__Primary_Account_Group,
                Master__Adroit__Account__Books = @Master__Adroit__Account__Books,
                Master__Adroit__Account__Book_Types = @Master__Adroit__Account__Book_Types,
                Master__Adroit__Account__Bill_From = @Master__Adroit__Account__Bill_From,
                Master__Adroit__Account__Book_Settings = @Master__Adroit__Account__Book_Settings,
                Master__Adroit__Location__City = @Master__Adroit__Location__City,
                Master__Adroit__Location__Taluka = @Master__Adroit__Location__Taluka,
                Master__Adroit__Location__District = @Master__Adroit__Location__District,
                Master__Adroit__Location__State = @Master__Adroit__Location__State,
                Master__Adroit__Location__Country = @Master__Adroit__Location__Country,
                Master__Adroit__GST__Rate = @Master__Adroit__GST__Rate,
                Master__Adroit__GST__Invoice_Types = @Master__Adroit__GST__Invoice_Types,
                Master__Adroit__GST__Ports = @Master__Adroit__GST__Ports,
                Master__Adroit__GST__Collections = @Master__Adroit__GST__Collections,
                Master__Adroit__Product__Colour = @Master__Adroit__Product__Colour,
                Master__Adroit__Product__Amount_Calculations = @Master__Adroit__Product__Amount_Calculations,
                Master__Adroit__Product__Size = @Master__Adroit__Product__Size,
                Master__Adroit__Product__Stock_Types = @Master__Adroit__Product__Stock_Types,
                Master__Adroit__Product__Quality_Types = @Master__Adroit__Product__Quality_Types,
                Master__Adroit__Transport__Packing = @Master__Adroit__Transport__Packing,
                Master__Adroit__Transport__Description = @Master__Adroit__Transport__Description,
                Master__Adroit__Transport__LR_Charges = @Master__Adroit__Transport__LR_Charges,
                Master__Customer__Firms = @Master__Customer__Firms,
                Master__Customer__Branches = @Master__Customer__Branches,
                Master__Customer__Users = @Master__Customer__Users,
                Master__Account__Add = @Master__Account__Add,
                Master__Account__Secondary_Account_Group = @Master__Account__Secondary_Account_Group,
                Master__Account__Primary_Account_Group = @Master__Account__Primary_Account_Group,
                Master__Product__Add = @Master__Product__Add,
                Master__Product__Design = @Master__Product__Design,
                Master__Product__Colour = @Master__Product__Colour,
                Master__Product__Size = @Master__Product__Size,
                Master__Product__Fabric = @Master__Product__Fabric,
                Master__Product__Group = @Master__Product__Group,
                Master__Product__Sub_Group = @Master__Product__Sub_Group,
                Master__Product__Shade = @Master__Product__Shade,
                Master__Product__Packing = @Master__Product__Packing,
                Master__Broker = @Master__Broker,
                Master__Machine = @Master__Machine,
                Master__Yarn_Shade = @Master__Yarn_Shade,
                Master__Yarn_Recipes = @Master__Yarn_Recipes,
                Master__Process = @Master__Process,
                Master__Cataloge = @Master__Cataloge,
                Master__Employee = @Master__Employee,
                Master__Location__City = @Master__Location__City,
                Master__Location__Branch_City_Mapping = @Master__Location__Branch_City_Mapping,
                Master__Vehicles = @Master__Vehicles,
                Master__Drivers = @Master__Drivers,
                Master__LR__Packing = @Master__LR__Packing,
                Master__LR__Description = @Master__LR__Description,
                Transaction__Booking__LR = @Transaction__Booking__LR,
                Transaction__Booking__Chalan = @Transaction__Booking__Chalan,
                Transaction__Booking__Invoice = @Transaction__Booking__Invoice,
                Transaction__Delivery__Chalan_Receive = @Transaction__Delivery__Chalan_Receive,
                Transaction__Delivery__Delivery_Invoice = @Transaction__Delivery__Delivery_Invoice,
                Transaction__Sales__Quotation = @Transaction__Sales__Quotation,
                Transaction__Sales__Praforma_Invoice = @Transaction__Sales__Praforma_Invoice,
                Transaction__Sales__Sales_Order = @Transaction__Sales__Sales_Order,
                Transaction__Sales__Chalan_Packing_Slip = @Transaction__Sales__Chalan_Packing_Slip,
                Transaction__Sales__Sales = @Transaction__Sales__Sales,
                Transaction__Sales__Sales_Return = @Transaction__Sales__Sales_Return,
                Transaction__Purchase__Purchase_Order = @Transaction__Purchase__Purchase_Order,
                Transaction__Purchase__Purchase_Chalan = @Transaction__Purchase__Purchase_Chalan,
                Transaction__Purchase__Purchase = @Transaction__Purchase__Purchase,
                Transaction__Purchase__Jobwork_Purchase = @Transaction__Purchase__Jobwork_Purchase,
                Transaction__Purchase__Purchase_Return = @Transaction__Purchase__Purchase_Return,
                Transaction__Purchase__General_Expenses = @Transaction__Purchase__General_Expenses,
                Transaction__Purchase__General_Expenses_Multi = @Transaction__Purchase__General_Expenses_Multi,
                Transaction__Credit_Note = @Transaction__Credit_Note,
                Transaction__Debit_Note = @Transaction__Debit_Note,
                Account__Payment__Bank_Payment = @Account__Payment__Bank_Payment,
                Account__Payment__Cash_Payment = @Account__Payment__Cash_Payment,
                Account__Receive__Bank_Receive = @Account__Receive__Bank_Receive,
                Account__Receive__Cash_Receive = @Account__Receive__Cash_Receive,
                Account__Account_Opening_Balance = @Account__Account_Opening_Balance,
                Account__Product_Opening_Stock = @Account__Product_Opening_Stock,
                Account__Journal_JV__General_JV = @Account__Journal_JV__General_JV,
                Account__Journal_JV__Bill_Base_JV = @Account__Journal_JV__Bill_Base_JV,
                Account__GST_Filling__GSTR_01 = @Account__GST_Filling__GSTR_01,
                Account__GST_Filling__GSTR_02_2A_2B = @Account__GST_Filling__GSTR_02_2A_2B,
                Account__GST_Filling__GSTR_03B = @Account__GST_Filling__GSTR_03B,
                Account__GST_Filling__GSTR_04_4B = @Account__GST_Filling__GSTR_04_4B,
                Account__GST_Filling__GSTR_09_9C = @Account__GST_Filling__GSTR_09_9C,
                Account__GST_Filling__ITC_04 = @Account__GST_Filling__ITC_04,
                Account__Reconsilation = @Account__Reconsilation,
                Account__Cash_Auto_Payment = @Account__Cash_Auto_Payment,
                Reports__SalesAndPurchase__Sales__Detail_Register = @Reports__SalesAndPurchase__Sales__Detail_Register,
                Reports__SalesAndPurchase__Sales__Summary_Register = @Reports__SalesAndPurchase__Sales__Summary_Register,
                Reports__SalesAndPurchase__Sales__Item_Wise_Register = @Reports__SalesAndPurchase__Sales__Item_Wise_Register,
                Reports__SalesAndPurchase__Sales__Monthly_Register = @Reports__SalesAndPurchase__Sales__Monthly_Register,
                Reports__SalesAndPurchase__Sales__Chalan_Regsiter = @Reports__SalesAndPurchase__Sales__Chalan_Regsiter,
                Reports__SalesAndPurchase__Sales__Sales_Order_Regsiter = @Reports__SalesAndPurchase__Sales__Sales_Order_Regsiter,
                Reports__SalesAndPurchase__Sales__Sales_Quotation_Register = @Reports__SalesAndPurchase__Sales__Sales_Quotation_Register,
                Reports__SalesAndPurchase__Sales__Proforma_Invoice_Register = @Reports__SalesAndPurchase__Sales__Proforma_Invoice_Register,
                Reports__SalesAndPurchase__Purchase__Detail_Register = @Reports__SalesAndPurchase__Purchase__Detail_Register,
                Reports__SalesAndPurchase__Purchase__Summary_Register = @Reports__SalesAndPurchase__Purchase__Summary_Register,
                Reports__SalesAndPurchase__Purchase__Item_Wise_Register = @Reports__SalesAndPurchase__Purchase__Item_Wise_Register,
                Reports__SalesAndPurchase__Purchase__Monthly_Register = @Reports__SalesAndPurchase__Purchase__Monthly_Register,
                Reports__SalesAndPurchase__Purchase__Chalan_Regsiter = @Reports__SalesAndPurchase__Purchase__Chalan_Regsiter,
                Reports__SalesAndPurchase__Purchase__Purchase_Order_Regsiter = @Reports__SalesAndPurchase__Purchase__Purchase_Order_Regsiter,
                Reports__SalesAndPurchase__Outstanding__Sales = @Reports__SalesAndPurchase__Outstanding__Sales,
                Reports__SalesAndPurchase__Outstanding__Sales_Vs_Ledger = @Reports__SalesAndPurchase__Outstanding__Sales_Vs_Ledger,
                Reports__SalesAndPurchase__Outstanding__Purchase = @Reports__SalesAndPurchase__Outstanding__Purchase,
                Reports__SalesAndPurchase__Outstanding__Purchase_Vs_Ledger = @Reports__SalesAndPurchase__Outstanding__Purchase_Vs_Ledger,
                Reports__SalesAndPurchase__Outstanding__Aiging_Register = @Reports__SalesAndPurchase__Outstanding__Aiging_Register,
                Reports__SalesAndPurchase__Outstanding__Interest_Calculator = @Reports__SalesAndPurchase__Outstanding__Interest_Calculator,
                Reports__BookAndRegister__LR_Booking_Register__LR_Register = @Reports__BookAndRegister__LR_Booking_Register__LR_Register,
                Reports__BookAndRegister__LR_Booking_Register__Stock_Register = @Reports__BookAndRegister__LR_Booking_Register__Stock_Register,
                Reports__BookAndRegister__LR_Booking_Register__Booking_Register = @Reports__BookAndRegister__LR_Booking_Register__Booking_Register,
                Reports__BookAndRegister__LR_Booking_Register__Daily_Summary = @Reports__BookAndRegister__LR_Booking_Register__Daily_Summary,
                Reports__BookAndRegister__LR_Booking_Register__Monthly_Summary = @Reports__BookAndRegister__LR_Booking_Register__Monthly_Summary,
                Reports__BookAndRegister__LR_Booking_Register__Chalan_Loading_Report = @Reports__BookAndRegister__LR_Booking_Register__Chalan_Loading_Report,
                Reports__BookAndRegister__LR_Booking_Register__Chalan_Monthly_Report = @Reports__BookAndRegister__LR_Booking_Register__Chalan_Monthly_Report,
                Reports__BookAndRegister__LR_Delivery_Register__LR_Register = @Reports__BookAndRegister__LR_Delivery_Register__LR_Register,
                Reports__BookAndRegister__LR_Delivery_Register__Stock_Register = @Reports__BookAndRegister__LR_Delivery_Register__Stock_Register,
                Reports__BookAndRegister__LR_Delivery_Register__Delivery_Register = @Reports__BookAndRegister__LR_Delivery_Register__Delivery_Register,
                Reports__BookAndRegister__LR_Delivery_Register__Daily_Summary = @Reports__BookAndRegister__LR_Delivery_Register__Daily_Summary,
                Reports__BookAndRegister__LR_Delivery_Register__Monthly_Summary = @Reports__BookAndRegister__LR_Delivery_Register__Monthly_Summary,
                Reports__BookAndRegister__LR_Delivery_Register__Chalan_Loading_Report = @Reports__BookAndRegister__LR_Delivery_Register__Chalan_Loading_Report,
                Reports__BookAndRegister__LR_Delivery_Register__Chalan_Monthly_Report = @Reports__BookAndRegister__LR_Delivery_Register__Chalan_Monthly_Report,
                Reports__BookAndRegister__Bank_Book = @Reports__BookAndRegister__Bank_Book,
                Reports__BookAndRegister__Cash_Book = @Reports__BookAndRegister__Cash_Book,
                Reports__BookAndRegister__Journal_Book = @Reports__BookAndRegister__Journal_Book,
                Reports__BookAndRegister__Day_Book = @Reports__BookAndRegister__Day_Book,
                Reports__BookAndRegister__Voucher_Book = @Reports__BookAndRegister__Voucher_Book,
                Reports__BookAndRegister__TDSAndTCS_Register = @Reports__BookAndRegister__TDSAndTCS_Register,
                Reports__BookAndRegister__Credit_Debit_Note_Register = @Reports__BookAndRegister__Credit_Debit_Note_Register,
                Reports__BookAndRegister__Payroll_Register = @Reports__BookAndRegister__Payroll_Register,
                Reports__BookAndRegister__Brokrage_Register = @Reports__BookAndRegister__Brokrage_Register,
                Reports__Stock__Stock_In_Out_Detail = @Reports__Stock__Stock_In_Out_Detail,
                Reports__Stock__Stock_Statement = @Reports__Stock__Stock_Statement,
                Reports__Stock__Item_Wise = @Reports__Stock__Item_Wise,
                Reports__Stock__Group_Wise = @Reports__Stock__Group_Wise,
                Reports__Stock__Stock_In_Process = @Reports__Stock__Stock_In_Process,
                Reports__Stock__Stock_In_Ware_House = @Reports__Stock__Stock_In_Ware_House,
                Reports__ProdAndInventory__Prod_Register__Yarn = @Reports__ProdAndInventory__Prod_Register__Yarn,
                Reports__ProdAndInventory__Prod_Register__Beam = @Reports__ProdAndInventory__Prod_Register__Beam,
                Reports__ProdAndInventory__Prod_Register__Grey = @Reports__ProdAndInventory__Prod_Register__Grey,
                Reports__ProdAndInventory__Prod_Register__General = @Reports__ProdAndInventory__Prod_Register__General,
                Reports__ProdAndInventory__Batch_Master_Register = @Reports__ProdAndInventory__Batch_Master_Register,
                Reports__ProdAndInventory__Issue_Register = @Reports__ProdAndInventory__Issue_Register,
                Reports__ProdAndInventory__Receive_Register = @Reports__ProdAndInventory__Receive_Register,
                Reports__Jobwork__Work_Issue_Chalan_Reg = @Reports__Jobwork__Work_Issue_Chalan_Reg,
                Reports__Jobwork__Work_Receive_Chalan_Reg = @Reports__Jobwork__Work_Receive_Chalan_Reg,
                Reports__Jobwork__Work_Pending_Reg = @Reports__Jobwork__Work_Pending_Reg,
                Reports__Jobwork__Jobwork_Receive_Chalan_Reg = @Reports__Jobwork__Jobwork_Receive_Chalan_Reg,
                Reports__Jobwork__Jobwork_Issue_Chalan_Reg = @Reports__Jobwork__Jobwork_Issue_Chalan_Reg,
                Reports__Jobwork__Jobwork_Pending_Reg = @Reports__Jobwork__Jobwork_Pending_Reg,
                Reports__Jobwork__Mill_Issue_Chalan_Reg = @Reports__Jobwork__Mill_Issue_Chalan_Reg,
                Reports__Jobwork__Mill_Receive_Chalan_Reg = @Reports__Jobwork__Mill_Receive_Chalan_Reg,
                Reports__Jobwork__Mill_Pending_Reg = @Reports__Jobwork__Mill_Pending_Reg,
                Reports__GST_Register__GSTR_01 = @Reports__GST_Register__GSTR_01,
                Reports__GST_Register__GSTR_02_2A_2B = @Reports__GST_Register__GSTR_02_2A_2B,
                Reports__GST_Register__GSTR_03B = @Reports__GST_Register__GSTR_03B,
                Reports__GST_Register__GSTR_04_4B = @Reports__GST_Register__GSTR_04_4B,
                Reports__GST_Register__GSTR_09_9C = @Reports__GST_Register__GSTR_09_9C,
                Reports__GST_Register__ITC_04 = @Reports__GST_Register__ITC_04,
                Reports__GST_Register__GSTR_SetOff = @Reports__GST_Register__GSTR_SetOff,
                Reports__GST_Register__GSTR_Reconsilation = @Reports__GST_Register__GSTR_Reconsilation,
                Reports__Account_Register__Ledger_Head_Print = @Reports__Account_Register__Ledger_Head_Print,
                Reports__Account_Register__Leadger = @Reports__Account_Register__Leadger,
                Reports__Account_Register__Ledger_Multi = @Reports__Account_Register__Ledger_Multi,
                Reports__Account_Register__Ledger_Month_Wise = @Reports__Account_Register__Ledger_Month_Wise,
                Reports__Account_Register__Interest_Calculator = @Reports__Account_Register__Interest_Calculator,
                Reports__Account_Register__Payable_Receivable = @Reports__Account_Register__Payable_Receivable,
                Reports__Financial_Reports__Trial_Balance_Summary = @Reports__Financial_Reports__Trial_Balance_Summary,
                Reports__Financial_Reports__Trial_Balance_Detail = @Reports__Financial_Reports__Trial_Balance_Detail,
                Reports__Financial_Reports__Trading_Account = @Reports__Financial_Reports__Trading_Account,
                Reports__Financial_Reports__ProfitAndLoss = @Reports__Financial_Reports__ProfitAndLoss,
                Reports__Financial_Reports__Balance_Sheet = @Reports__Financial_Reports__Balance_Sheet,
                Reports__Financial_Reports__Balance_Sheet_Schedule = @Reports__Financial_Reports__Balance_Sheet_Schedule,
                Inventory__Production__Consumption_BOM__Batch_Master = @Inventory__Production__Consumption_BOM__Batch_Master,
                Inventory__Production__Consumption_BOM__Yarn_Master = @Inventory__Production__Consumption_BOM__Yarn_Master,
                Inventory__Production__Consumption_BOM__Grey_Master = @Inventory__Production__Consumption_BOM__Grey_Master,
                Inventory__Production__Consumption_BOM__Saree_Master = @Inventory__Production__Consumption_BOM__Saree_Master,
                Inventory__Production__Gen_Prod__Production = @Inventory__Production__Gen_Prod__Production,
                Inventory__Production__Gen_Prod__Yarn_Production = @Inventory__Production__Gen_Prod__Yarn_Production,
                Inventory__Production__Gen_Prod__Beam_Production = @Inventory__Production__Gen_Prod__Beam_Production,
                Inventory__Production__Gen_Prod__Grey_Production = @Inventory__Production__Gen_Prod__Grey_Production,
                Inventory__Production__Gen_Prod__Saree_Production = @Inventory__Production__Gen_Prod__Saree_Production,
                Inventory__IssueAndReceive__Yarn__Issue = @Inventory__IssueAndReceive__Yarn__Issue,
                Inventory__IssueAndReceive__Yarn__Receive = @Inventory__IssueAndReceive__Yarn__Receive,
                Inventory__IssueAndReceive__Beam__Issue_for_OutsideWork = @Inventory__IssueAndReceive__Beam__Issue_for_OutsideWork,
                Inventory__IssueAndReceive__Beam__Receive_From_Yarn_Issue = @Inventory__IssueAndReceive__Beam__Receive_From_Yarn_Issue,
                Inventory__IssueAndReceive__Grey__Issue_for_OutsideWork = @Inventory__IssueAndReceive__Grey__Issue_for_OutsideWork,
                Inventory__IssueAndReceive__Grey__Receive_From_OutsideWork = @Inventory__IssueAndReceive__Grey__Receive_From_OutsideWork,
                Inventory__Beam_Entry = @Inventory__Beam_Entry,
                Inventory__Inventory__Issue = @Inventory__Inventory__Issue,
                Inventory__Inventory__Receive = @Inventory__Inventory__Receive,
                Inventory__Jobwork__Work_Dispach = @Inventory__Jobwork__Work_Dispach,
                Inventory__Jobwork__Work_Receive = @Inventory__Jobwork__Work_Receive,
                Inventory__Jobwork__Job_Receive = @Inventory__Jobwork__Job_Receive,
                Inventory__Jobwork__Job_Issue = @Inventory__Jobwork__Job_Issue,
                Inventory__Mill_Jobwork__Issue = @Inventory__Mill_Jobwork__Issue,
                Inventory__Mill_Jobwork__Receive = @Inventory__Mill_Jobwork__Receive,
                Inventory__Mill_Jobwork__Job_Receive = @Inventory__Mill_Jobwork__Job_Receive,
                Inventory__Mill_Jobwork__Job_Issue = @Inventory__Mill_Jobwork__Job_Issue,
                Inventory__Cutting_Process__Taka_to_Pcs = @Inventory__Cutting_Process__Taka_to_Pcs,
                SettingsAndUtilities__Book_Setting__Books = @SettingsAndUtilities__Book_Setting__Books,
                SettingsAndUtilities__Book_Setting__Multi_Print_Invoice = @SettingsAndUtilities__Book_Setting__Multi_Print_Invoice,
                SettingsAndUtilities__Book_Setting__Multi_Print_Vocher = @SettingsAndUtilities__Book_Setting__Multi_Print_Vocher,
                SettingsAndUtilities__Merge__Account_Master = @SettingsAndUtilities__Merge__Account_Master,
                SettingsAndUtilities__Merge__Product_Master = @SettingsAndUtilities__Merge__Product_Master,
                SettingsAndUtilities__Merge__Broker_Master = @SettingsAndUtilities__Merge__Broker_Master,
                SettingsAndUtilities__Merge__City_Master = @SettingsAndUtilities__Merge__City_Master,
                SettingsAndUtilities__Merge__Vehicle_Master = @SettingsAndUtilities__Merge__Vehicle_Master,
                SettingsAndUtilities__Merge__Driver_Master = @SettingsAndUtilities__Merge__Driver_Master,
                SettingsAndUtilities__Merge__Packing_Master = @SettingsAndUtilities__Merge__Packing_Master,
                SettingsAndUtilities__Merge__Description_Master = @SettingsAndUtilities__Merge__Description_Master,
                SettingsAndUtilities__Merge__Taka_Merge = @SettingsAndUtilities__Merge__Taka_Merge,
                SettingsAndUtilities__Merge__Taka_Demerge = @SettingsAndUtilities__Merge__Taka_Demerge,
                SettingsAndUtilities__Year__Create_New_Year = @SettingsAndUtilities__Year__Create_New_Year,
                SettingsAndUtilities__Year__Year_End_Process = @SettingsAndUtilities__Year__Year_End_Process,
                SettingsAndUtilities__Transfer_Next_Year__Closing_Stock = @SettingsAndUtilities__Transfer_Next_Year__Closing_Stock,
                SettingsAndUtilities__Transfer_Next_Year__Closing_Amount = @SettingsAndUtilities__Transfer_Next_Year__Closing_Amount,
                SettingsAndUtilities__Transfer_Next_Year__Sales_Invoice = @SettingsAndUtilities__Transfer_Next_Year__Sales_Invoice,
                SettingsAndUtilities__Transfer_Next_Year__Purchase_Invoice = @SettingsAndUtilities__Transfer_Next_Year__Purchase_Invoice,
                SettingsAndUtilities__Transfer_Next_Year__Work_Dispach_For_Job = @SettingsAndUtilities__Transfer_Next_Year__Work_Dispach_For_Job,
                SettingsAndUtilities__Transfer_Next_Year__Job_Receive_For_Work = @SettingsAndUtilities__Transfer_Next_Year__Job_Receive_For_Work,
                SettingsAndUtilities__Transfer_Next_Year__Mill_Issue = @SettingsAndUtilities__Transfer_Next_Year__Mill_Issue,
                SettingsAndUtilities__Transfer_Next_Year__Mill_Job_Receive = @SettingsAndUtilities__Transfer_Next_Year__Mill_Job_Receive,
                SettingsAndUtilities__Transfer_Next_Year__Taka_Production = @SettingsAndUtilities__Transfer_Next_Year__Taka_Production,
                SettingsAndUtilities__Transfer_Next_Year__Box_Production = @SettingsAndUtilities__Transfer_Next_Year__Box_Production,
                SettingsAndUtilities__Delete_Previous_Year__Closing_Stock = @SettingsAndUtilities__Delete_Previous_Year__Closing_Stock,
                SettingsAndUtilities__Delete_Previous_Year__Closing_Amount = @SettingsAndUtilities__Delete_Previous_Year__Closing_Amount,
                SettingsAndUtilities__Delete_Previous_Year__Sales_Invoice = @SettingsAndUtilities__Delete_Previous_Year__Sales_Invoice,
                SettingsAndUtilities__Delete_Previous_Year__Purchase_Invoice = @SettingsAndUtilities__Delete_Previous_Year__Purchase_Invoice,
                SettingsAndUtilities__Delete_Previous_Year__Work_Dispach_For_Job = @SettingsAndUtilities__Delete_Previous_Year__Work_Dispach_For_Job,
                SettingsAndUtilities__Delete_Previous_Year__Job_Receive_For_Work = @SettingsAndUtilities__Delete_Previous_Year__Job_Receive_For_Work,
                SettingsAndUtilities__Delete_Previous_Year__Mill_Issue = @SettingsAndUtilities__Delete_Previous_Year__Mill_Issue,
                SettingsAndUtilities__Delete_Previous_Year__Mill_Job_Receive = @SettingsAndUtilities__Delete_Previous_Year__Mill_Job_Receive,
                SettingsAndUtilities__Delete_Previous_Year__Taka_Production = @SettingsAndUtilities__Delete_Previous_Year__Taka_Production,
                SettingsAndUtilities__Delete_Previous_Year__Box_Production = @SettingsAndUtilities__Delete_Previous_Year__Box_Production,
                SettingsAndUtilities__Transport_Setting__Firm = @SettingsAndUtilities__Transport_Setting__Firm,
                SettingsAndUtilities__Transport_Setting__Branch = @SettingsAndUtilities__Transport_Setting__Branch,
                SettingsAndUtilities__Transport_Setting__LR_Rate = @SettingsAndUtilities__Transport_Setting__LR_Rate,
                SettingsAndUtilities__Transport_Setting__Contract_Rate = @SettingsAndUtilities__Transport_Setting__Contract_Rate,
                SettingsAndUtilities__Transport_Setting__LR_Booking_Range = @SettingsAndUtilities__Transport_Setting__LR_Booking_Range,
                ModifiedById = @UserId, 
                ModifiedOn = GETUTCDate()
            WHERE Id = @Id 
            --WHERE SoftwareId = @SoftwareId 
            --    AND @SoftwarePlanId = @SoftwarePlanId 
            --    AND @CustomerId = @CustomerId 
            --    AND @CusomerFirmId = @CusomerFirmId
            --    AND @CustomerFirmBranchId = @CustomerFirmBranchId
            --    AND @CustomerUserId = @CustomerUserId
        END
        ELSE 
        BEGIN
            INSERT INTO MenuSetting (SoftwareId, SoftwarePlanId, CustomerId, CusomerFirmId, CustomerFirmBranchId, CustomerUserId, 
                    Master__Adroit__Software__Software_Master, Master__Adroit__Software__Plan, Master__Adroit__Software__Businesses, 
                    Master__Adroit__Customer__Customers, Master__Adroit__Customer__Branch_Types, Master__Adroit__Customer__Menu_Setting, 
                    Master__Adroit__Customer__Box_Setting, Master__Adroit__Account__Accounts, Master__Adroit__Account__Secondary_Account_Group, 
                    Master__Adroit__Account__Primary_Account_Group, Master__Adroit__Account__Books, Master__Adroit__Account__Book_Types, 
                    Master__Adroit__Account__Bill_From, Master__Adroit__Account__Book_Settings, Master__Adroit__Location__City, 
                    Master__Adroit__Location__Taluka, Master__Adroit__Location__District, Master__Adroit__Location__State, 
                    Master__Adroit__Location__Country, Master__Adroit__GST__Rate, Master__Adroit__GST__Invoice_Types, 
                    Master__Adroit__GST__Ports, Master__Adroit__GST__Collections, Master__Adroit__Product__Colour, 
                    Master__Adroit__Product__Amount_Calculations, Master__Adroit__Product__Size, Master__Adroit__Product__Stock_Types, 
                    Master__Adroit__Product__Quality_Types, Master__Adroit__Transport__Packing, Master__Adroit__Transport__Description, 
                    Master__Adroit__Transport__LR_Charges, Master__Customer__Firms, Master__Customer__Branches, Master__Customer__Users, 
                    Master__Account__Add, Master__Account__Secondary_Account_Group, Master__Account__Primary_Account_Group, 
                    Master__Product__Add, Master__Product__Design, Master__Product__Colour, Master__Product__Size, Master__Product__Fabric, 
                    Master__Product__Group, Master__Product__Sub_Group, Master__Product__Shade, Master__Product__Packing, Master__Broker, 
                    Master__Machine, Master__Yarn_Shade, Master__Yarn_Recipes, Master__Process, Master__Cataloge, Master__Employee, 
                    Master__Location__City, Master__Location__Branch_City_Mapping, Master__Vehicles, Master__Drivers, Master__LR__Packing, 
                    Master__LR__Description, 
                    Transaction__Booking__LR, Transaction__Booking__Chalan, Transaction__Booking__Invoice, Transaction__Delivery__Chalan_Receive, 
                    Transaction__Delivery__Delivery_Invoice, Transaction__Sales__Quotation, Transaction__Sales__Praforma_Invoice, 
                    Transaction__Sales__Sales_Order, Transaction__Sales__Chalan_Packing_Slip, Transaction__Sales__Sales, Transaction__Sales__Sales_Return, 
                    Transaction__Purchase__Purchase_Order, Transaction__Purchase__Purchase_Chalan, Transaction__Purchase__Purchase, 
                    Transaction__Purchase__Jobwork_Purchase, Transaction__Purchase__Purchase_Return, Transaction__Purchase__General_Expenses, 
                    Transaction__Purchase__General_Expenses_Multi, Transaction__Credit_Note, Transaction__Debit_Note, Account__Payment__Bank_Payment, 
                    Account__Payment__Cash_Payment, Account__Receive__Bank_Receive, Account__Receive__Cash_Receive, Account__Account_Opening_Balance, 
                    Account__Product_Opening_Stock, Account__Journal_JV__General_JV, Account__Journal_JV__Bill_Base_JV, Account__GST_Filling__GSTR_01, 
                    Account__GST_Filling__GSTR_02_2A_2B, Account__GST_Filling__GSTR_03B, Account__GST_Filling__GSTR_04_4B, 
                    Account__GST_Filling__GSTR_09_9C, Account__GST_Filling__ITC_04, Account__Reconsilation, Account__Cash_Auto_Payment, 
                    Reports__SalesAndPurchase__Sales__Detail_Register, Reports__SalesAndPurchase__Sales__Summary_Register, 
                    Reports__SalesAndPurchase__Sales__Item_Wise_Register, Reports__SalesAndPurchase__Sales__Monthly_Register, 
                    Reports__SalesAndPurchase__Sales__Chalan_Regsiter, Reports__SalesAndPurchase__Sales__Sales_Order_Regsiter, 
                    Reports__SalesAndPurchase__Sales__Sales_Quotation_Register, Reports__SalesAndPurchase__Sales__Proforma_Invoice_Register, 
                    Reports__SalesAndPurchase__Purchase__Detail_Register, Reports__SalesAndPurchase__Purchase__Summary_Register, 
                    Reports__SalesAndPurchase__Purchase__Item_Wise_Register, Reports__SalesAndPurchase__Purchase__Monthly_Register, 
                    Reports__SalesAndPurchase__Purchase__Chalan_Regsiter, Reports__SalesAndPurchase__Purchase__Purchase_Order_Regsiter, 
                    Reports__SalesAndPurchase__Outstanding__Sales, Reports__SalesAndPurchase__Outstanding__Sales_Vs_Ledger, 
                    Reports__SalesAndPurchase__Outstanding__Purchase, Reports__SalesAndPurchase__Outstanding__Purchase_Vs_Ledger, 
                    Reports__SalesAndPurchase__Outstanding__Aiging_Register, Reports__SalesAndPurchase__Outstanding__Interest_Calculator, 
                    Reports__BookAndRegister__LR_Booking_Register__LR_Register, Reports__BookAndRegister__LR_Booking_Register__Stock_Register, 
                    Reports__BookAndRegister__LR_Booking_Register__Booking_Register, Reports__BookAndRegister__LR_Booking_Register__Daily_Summary, 
                    Reports__BookAndRegister__LR_Booking_Register__Monthly_Summary, Reports__BookAndRegister__LR_Booking_Register__Chalan_Loading_Report, 
                    Reports__BookAndRegister__LR_Booking_Register__Chalan_Monthly_Report, Reports__BookAndRegister__LR_Delivery_Register__LR_Register, 
                    Reports__BookAndRegister__LR_Delivery_Register__Stock_Register, Reports__BookAndRegister__LR_Delivery_Register__Delivery_Register, 
                    Reports__BookAndRegister__LR_Delivery_Register__Daily_Summary, Reports__BookAndRegister__LR_Delivery_Register__Monthly_Summary, 
                    Reports__BookAndRegister__LR_Delivery_Register__Chalan_Loading_Report, 
                    Reports__BookAndRegister__LR_Delivery_Register__Chalan_Monthly_Report, Reports__BookAndRegister__Bank_Book, 
                    Reports__BookAndRegister__Cash_Book, Reports__BookAndRegister__Journal_Book, Reports__BookAndRegister__Day_Book, 
                    Reports__BookAndRegister__Voucher_Book, Reports__BookAndRegister__TDSAndTCS_Register, Reports__BookAndRegister__Credit_Debit_Note_Register,
                    Reports__BookAndRegister__Payroll_Register, Reports__BookAndRegister__Brokrage_Register, Reports__Stock__Stock_In_Out_Detail, 
                    Reports__Stock__Stock_Statement, Reports__Stock__Item_Wise, Reports__Stock__Group_Wise, Reports__Stock__Stock_In_Process, 
                    Reports__Stock__Stock_In_Ware_House, Reports__ProdAndInventory__Prod_Register__Yarn, Reports__ProdAndInventory__Prod_Register__Beam, 
                    Reports__ProdAndInventory__Prod_Register__Grey, Reports__ProdAndInventory__Prod_Register__General, 
                    Reports__ProdAndInventory__Batch_Master_Register, Reports__ProdAndInventory__Issue_Register, Reports__ProdAndInventory__Receive_Register,
                    Reports__Jobwork__Work_Issue_Chalan_Reg, Reports__Jobwork__Work_Receive_Chalan_Reg, Reports__Jobwork__Work_Pending_Reg, 
                    Reports__Jobwork__Jobwork_Receive_Chalan_Reg, Reports__Jobwork__Jobwork_Issue_Chalan_Reg, Reports__Jobwork__Jobwork_Pending_Reg, 
                    Reports__Jobwork__Mill_Issue_Chalan_Reg, Reports__Jobwork__Mill_Receive_Chalan_Reg, Reports__Jobwork__Mill_Pending_Reg, 
                    Reports__GST_Register__GSTR_01, Reports__GST_Register__GSTR_02_2A_2B, Reports__GST_Register__GSTR_03B, Reports__GST_Register__GSTR_04_4B, 
                    Reports__GST_Register__GSTR_09_9C, Reports__GST_Register__ITC_04, Reports__GST_Register__GSTR_SetOff, 
                    Reports__GST_Register__GSTR_Reconsilation, Reports__Account_Register__Ledger_Head_Print, Reports__Account_Register__Leadger, 
                    Reports__Account_Register__Ledger_Multi, Reports__Account_Register__Ledger_Month_Wise, Reports__Account_Register__Interest_Calculator, 
                    Reports__Account_Register__Payable_Receivable, Reports__Financial_Reports__Trial_Balance_Summary, 
                    Reports__Financial_Reports__Trial_Balance_Detail, Reports__Financial_Reports__Trading_Account, Reports__Financial_Reports__ProfitAndLoss, 
                    Reports__Financial_Reports__Balance_Sheet, Reports__Financial_Reports__Balance_Sheet_Schedule, 
                    Inventory__Production__Consumption_BOM__Batch_Master, Inventory__Production__Consumption_BOM__Yarn_Master, 
                    Inventory__Production__Consumption_BOM__Grey_Master, Inventory__Production__Consumption_BOM__Saree_Master, 
                    Inventory__Production__Gen_Prod__Production, Inventory__Production__Gen_Prod__Yarn_Production, 
                    Inventory__Production__Gen_Prod__Beam_Production, Inventory__Production__Gen_Prod__Grey_Production, 
                    Inventory__Production__Gen_Prod__Saree_Production, Inventory__IssueAndReceive__Yarn__Issue, Inventory__IssueAndReceive__Yarn__Receive, 
                    Inventory__IssueAndReceive__Beam__Issue_for_OutsideWork, Inventory__IssueAndReceive__Beam__Receive_From_Yarn_Issue, 
                    Inventory__IssueAndReceive__Grey__Issue_for_OutsideWork, Inventory__IssueAndReceive__Grey__Receive_From_OutsideWork, 
                    Inventory__Beam_Entry, Inventory__Inventory__Issue, Inventory__Inventory__Receive, Inventory__Jobwork__Work_Dispach, 
                    Inventory__Jobwork__Work_Receive, Inventory__Jobwork__Job_Receive, Inventory__Jobwork__Job_Issue, Inventory__Mill_Jobwork__Issue, 
                    Inventory__Mill_Jobwork__Receive, Inventory__Mill_Jobwork__Job_Receive, Inventory__Mill_Jobwork__Job_Issue, Inventory__Cutting_Process__Taka_to_Pcs,
                    SettingsAndUtilities__Book_Setting__Books, SettingsAndUtilities__Book_Setting__Multi_Print_Invoice,
                    SettingsAndUtilities__Book_Setting__Multi_Print_Vocher, SettingsAndUtilities__Merge__Account_Master, 
                    SettingsAndUtilities__Merge__Product_Master, SettingsAndUtilities__Merge__Broker_Master, SettingsAndUtilities__Merge__City_Master, 
                    SettingsAndUtilities__Merge__Vehicle_Master, SettingsAndUtilities__Merge__Driver_Master, SettingsAndUtilities__Merge__Packing_Master, 
                    SettingsAndUtilities__Merge__Description_Master, SettingsAndUtilities__Merge__Taka_Merge, SettingsAndUtilities__Merge__Taka_Demerge, 
                    SettingsAndUtilities__Year__Create_New_Year, SettingsAndUtilities__Year__Year_End_Process, SettingsAndUtilities__Transfer_Next_Year__Closing_Stock, 
                    SettingsAndUtilities__Transfer_Next_Year__Closing_Amount, SettingsAndUtilities__Transfer_Next_Year__Sales_Invoice, 
                    SettingsAndUtilities__Transfer_Next_Year__Purchase_Invoice, SettingsAndUtilities__Transfer_Next_Year__Work_Dispach_For_Job, 
                    SettingsAndUtilities__Transfer_Next_Year__Job_Receive_For_Work, SettingsAndUtilities__Transfer_Next_Year__Mill_Issue, 
                    SettingsAndUtilities__Transfer_Next_Year__Mill_Job_Receive, SettingsAndUtilities__Transfer_Next_Year__Taka_Production, 
                    SettingsAndUtilities__Transfer_Next_Year__Box_Production, SettingsAndUtilities__Delete_Previous_Year__Closing_Stock, 
                    SettingsAndUtilities__Delete_Previous_Year__Closing_Amount, SettingsAndUtilities__Delete_Previous_Year__Sales_Invoice, 
                    SettingsAndUtilities__Delete_Previous_Year__Purchase_Invoice, SettingsAndUtilities__Delete_Previous_Year__Work_Dispach_For_Job, 
                    SettingsAndUtilities__Delete_Previous_Year__Job_Receive_For_Work, SettingsAndUtilities__Delete_Previous_Year__Mill_Issue, 
                    SettingsAndUtilities__Delete_Previous_Year__Mill_Job_Receive, SettingsAndUtilities__Delete_Previous_Year__Taka_Production, 
                    SettingsAndUtilities__Delete_Previous_Year__Box_Production, SettingsAndUtilities__Transport_Setting__Firm, 
                    SettingsAndUtilities__Transport_Setting__Branch, SettingsAndUtilities__Transport_Setting__LR_Rate, 
                    SettingsAndUtilities__Transport_Setting__Contract_Rate, SettingsAndUtilities__Transport_Setting__LR_Booking_Range, 
                    AddedOn, AddedById)
                VALUES (@SoftwareId, @SoftwarePlanId, @CustomerId, @CusomerFirmId, @CustomerFirmBranchId, @CustomerUserId,
                    @Master__Adroit__Software__Software_Master, @Master__Adroit__Software__Plan, @Master__Adroit__Software__Businesses,
                    @Master__Adroit__Customer__Customers, @Master__Adroit__Customer__Branch_Types, @Master__Adroit__Customer__Menu_Setting,
                    @Master__Adroit__Customer__Box_Setting, @Master__Adroit__Account__Accounts, @Master__Adroit__Account__Secondary_Account_Group,
                    @Master__Adroit__Account__Primary_Account_Group, @Master__Adroit__Account__Books, @Master__Adroit__Account__Book_Types,
                    @Master__Adroit__Account__Bill_From, @Master__Adroit__Account__Book_Settings, @Master__Adroit__Location__City,
                    @Master__Adroit__Location__Taluka, @Master__Adroit__Location__District, @Master__Adroit__Location__State,
                    @Master__Adroit__Location__Country, @Master__Adroit__GST__Rate, @Master__Adroit__GST__Invoice_Types,
                    @Master__Adroit__GST__Ports, @Master__Adroit__GST__Collections, @Master__Adroit__Product__Colour,
                    @Master__Adroit__Product__Amount_Calculations, @Master__Adroit__Product__Size, @Master__Adroit__Product__Stock_Types,
                    @Master__Adroit__Product__Quality_Types, @Master__Adroit__Transport__Packing, @Master__Adroit__Transport__Description,
                    @Master__Adroit__Transport__LR_Charges, @Master__Customer__Firms, @Master__Customer__Branches, @Master__Customer__Users,
                    @Master__Account__Add, @Master__Account__Secondary_Account_Group, @Master__Account__Primary_Account_Group,
                    @Master__Product__Add, @Master__Product__Design, @Master__Product__Colour, @Master__Product__Size, @Master__Product__Fabric,
                    @Master__Product__Group, @Master__Product__Sub_Group, @Master__Product__Shade, @Master__Product__Packing, @Master__Broker,
                    @Master__Machine, @Master__Yarn_Shade, @Master__Yarn_Recipes, @Master__Process, @Master__Cataloge, @Master__Employee,
                    @Master__Location__City, @Master__Location__Branch_City_Mapping, @Master__Vehicles, @Master__Drivers, @Master__LR__Packing,
                    @Master__LR__Description,
                    @Transaction__Booking__LR, @Transaction__Booking__Chalan, @Transaction__Booking__Invoice, @Transaction__Delivery__Chalan_Receive,
                    @Transaction__Delivery__Delivery_Invoice, @Transaction__Sales__Quotation, @Transaction__Sales__Praforma_Invoice,
                    @Transaction__Sales__Sales_Order, @Transaction__Sales__Chalan_Packing_Slip, @Transaction__Sales__Sales, @Transaction__Sales__Sales_Return,
                    @Transaction__Purchase__Purchase_Order, @Transaction__Purchase__Purchase_Chalan, @Transaction__Purchase__Purchase,
                    @Transaction__Purchase__Jobwork_Purchase, @Transaction__Purchase__Purchase_Return, @Transaction__Purchase__General_Expenses,
                    @Transaction__Purchase__General_Expenses_Multi, @Transaction__Credit_Note, @Transaction__Debit_Note, @Account__Payment__Bank_Payment,
                    @Account__Payment__Cash_Payment, @Account__Receive__Bank_Receive, @Account__Receive__Cash_Receive, @Account__Account_Opening_Balance,
                    @Account__Product_Opening_Stock, @Account__Journal_JV__General_JV, @Account__Journal_JV__Bill_Base_JV, @Account__GST_Filling__GSTR_01,
                    @Account__GST_Filling__GSTR_02_2A_2B, @Account__GST_Filling__GSTR_03B, @Account__GST_Filling__GSTR_04_4B,
                    @Account__GST_Filling__GSTR_09_9C, @Account__GST_Filling__ITC_04, @Account__Reconsilation, @Account__Cash_Auto_Payment,
                    @Reports__SalesAndPurchase__Sales__Detail_Register, @Reports__SalesAndPurchase__Sales__Summary_Register,
                    @Reports__SalesAndPurchase__Sales__Item_Wise_Register, @Reports__SalesAndPurchase__Sales__Monthly_Register,
                    @Reports__SalesAndPurchase__Sales__Chalan_Regsiter, @Reports__SalesAndPurchase__Sales__Sales_Order_Regsiter,
                    @Reports__SalesAndPurchase__Sales__Sales_Quotation_Register, @Reports__SalesAndPurchase__Sales__Proforma_Invoice_Register,
                    @Reports__SalesAndPurchase__Purchase__Detail_Register, @Reports__SalesAndPurchase__Purchase__Summary_Register,
                    @Reports__SalesAndPurchase__Purchase__Item_Wise_Register, @Reports__SalesAndPurchase__Purchase__Monthly_Register,
                    @Reports__SalesAndPurchase__Purchase__Chalan_Regsiter, @Reports__SalesAndPurchase__Purchase__Purchase_Order_Regsiter,
                    @Reports__SalesAndPurchase__Outstanding__Sales, @Reports__SalesAndPurchase__Outstanding__Sales_Vs_Ledger,
                    @Reports__SalesAndPurchase__Outstanding__Purchase, @Reports__SalesAndPurchase__Outstanding__Purchase_Vs_Ledger,
                    @Reports__SalesAndPurchase__Outstanding__Aiging_Register, @Reports__SalesAndPurchase__Outstanding__Interest_Calculator,
                    @Reports__BookAndRegister__LR_Booking_Register__LR_Register, @Reports__BookAndRegister__LR_Booking_Register__Stock_Register,
                    @Reports__BookAndRegister__LR_Booking_Register__Booking_Register, @Reports__BookAndRegister__LR_Booking_Register__Daily_Summary,
                    @Reports__BookAndRegister__LR_Booking_Register__Monthly_Summary, @Reports__BookAndRegister__LR_Booking_Register__Chalan_Loading_Report,
                    @Reports__BookAndRegister__LR_Booking_Register__Chalan_Monthly_Report, @Reports__BookAndRegister__LR_Delivery_Register__LR_Register,
                    @Reports__BookAndRegister__LR_Delivery_Register__Stock_Register, @Reports__BookAndRegister__LR_Delivery_Register__Delivery_Register,
                    @Reports__BookAndRegister__LR_Delivery_Register__Daily_Summary, @Reports__BookAndRegister__LR_Delivery_Register__Monthly_Summary,
                    @Reports__BookAndRegister__LR_Delivery_Register__Chalan_Loading_Report,
                    @Reports__BookAndRegister__LR_Delivery_Register__Chalan_Monthly_Report, @Reports__BookAndRegister__Bank_Book,
                    @Reports__BookAndRegister__Cash_Book, @Reports__BookAndRegister__Journal_Book, @Reports__BookAndRegister__Day_Book,
                    @Reports__BookAndRegister__Voucher_Book, @Reports__BookAndRegister__TDSAndTCS_Register, @Reports__BookAndRegister__Credit_Debit_Note_Register,
                    @Reports__BookAndRegister__Payroll_Register, @Reports__BookAndRegister__Brokrage_Register, @Reports__Stock__Stock_In_Out_Detail,
                    @Reports__Stock__Stock_Statement, @Reports__Stock__Item_Wise, @Reports__Stock__Group_Wise, @Reports__Stock__Stock_In_Process,
                    @Reports__Stock__Stock_In_Ware_House, @Reports__ProdAndInventory__Prod_Register__Yarn, @Reports__ProdAndInventory__Prod_Register__Beam,
                    @Reports__ProdAndInventory__Prod_Register__Grey, @Reports__ProdAndInventory__Prod_Register__General,
                    @Reports__ProdAndInventory__Batch_Master_Register, @Reports__ProdAndInventory__Issue_Register, @Reports__ProdAndInventory__Receive_Register,
                    @Reports__Jobwork__Work_Issue_Chalan_Reg, @Reports__Jobwork__Work_Receive_Chalan_Reg, @Reports__Jobwork__Work_Pending_Reg,
                    @Reports__Jobwork__Jobwork_Receive_Chalan_Reg, @Reports__Jobwork__Jobwork_Issue_Chalan_Reg, @Reports__Jobwork__Jobwork_Pending_Reg,
                    @Reports__Jobwork__Mill_Issue_Chalan_Reg, @Reports__Jobwork__Mill_Receive_Chalan_Reg, @Reports__Jobwork__Mill_Pending_Reg,
                    @Reports__GST_Register__GSTR_01, @Reports__GST_Register__GSTR_02_2A_2B, @Reports__GST_Register__GSTR_03B, @Reports__GST_Register__GSTR_04_4B,
                    @Reports__GST_Register__GSTR_09_9C, @Reports__GST_Register__ITC_04, @Reports__GST_Register__GSTR_SetOff,
                    @Reports__GST_Register__GSTR_Reconsilation, @Reports__Account_Register__Ledger_Head_Print, @Reports__Account_Register__Leadger,
                    @Reports__Account_Register__Ledger_Multi, @Reports__Account_Register__Ledger_Month_Wise, @Reports__Account_Register__Interest_Calculator,
                    @Reports__Account_Register__Payable_Receivable, @Reports__Financial_Reports__Trial_Balance_Summary,
                    @Reports__Financial_Reports__Trial_Balance_Detail, @Reports__Financial_Reports__Trading_Account, @Reports__Financial_Reports__ProfitAndLoss,
                    @Reports__Financial_Reports__Balance_Sheet, @Reports__Financial_Reports__Balance_Sheet_Schedule,
                    @Inventory__Production__Consumption_BOM__Batch_Master, @Inventory__Production__Consumption_BOM__Yarn_Master,
                    @Inventory__Production__Consumption_BOM__Grey_Master, @Inventory__Production__Consumption_BOM__Saree_Master,
                    @Inventory__Production__Gen_Prod__Production, @Inventory__Production__Gen_Prod__Yarn_Production,
                    @Inventory__Production__Gen_Prod__Beam_Production, @Inventory__Production__Gen_Prod__Grey_Production,
                    @Inventory__Production__Gen_Prod__Saree_Production, @Inventory__IssueAndReceive__Yarn__Issue, @Inventory__IssueAndReceive__Yarn__Receive,
                    @Inventory__IssueAndReceive__Beam__Issue_for_OutsideWork, @Inventory__IssueAndReceive__Beam__Receive_From_Yarn_Issue,
                    @Inventory__IssueAndReceive__Grey__Issue_for_OutsideWork, @Inventory__IssueAndReceive__Grey__Receive_From_OutsideWork,
                    @Inventory__Beam_Entry, @Inventory__Inventory__Issue, @Inventory__Inventory__Receive, @Inventory__Jobwork__Work_Dispach,
                    @Inventory__Jobwork__Work_Receive, @Inventory__Jobwork__Job_Receive, @Inventory__Jobwork__Job_Issue, @Inventory__Mill_Jobwork__Issue,
                    @Inventory__Mill_Jobwork__Receive, @Inventory__Mill_Jobwork__Job_Receive, @Inventory__Mill_Jobwork__Job_Issue, @Inventory__Cutting_Process__Taka_to_Pcs,
                    @SettingsAndUtilities__Book_Setting__Books, @SettingsAndUtilities__Book_Setting__Multi_Print_Invoice,
                    @SettingsAndUtilities__Book_Setting__Multi_Print_Vocher, @SettingsAndUtilities__Merge__Account_Master,
                    @SettingsAndUtilities__Merge__Product_Master, @SettingsAndUtilities__Merge__Broker_Master, @SettingsAndUtilities__Merge__City_Master,
                    @SettingsAndUtilities__Merge__Vehicle_Master, @SettingsAndUtilities__Merge__Driver_Master, @SettingsAndUtilities__Merge__Packing_Master,
                    @SettingsAndUtilities__Merge__Description_Master, @SettingsAndUtilities__Merge__Taka_Merge, @SettingsAndUtilities__Merge__Taka_Demerge,
                    @SettingsAndUtilities__Year__Create_New_Year, @SettingsAndUtilities__Year__Year_End_Process, @SettingsAndUtilities__Transfer_Next_Year__Closing_Stock,
                    @SettingsAndUtilities__Transfer_Next_Year__Closing_Amount, @SettingsAndUtilities__Transfer_Next_Year__Sales_Invoice,
                    @SettingsAndUtilities__Transfer_Next_Year__Purchase_Invoice, @SettingsAndUtilities__Transfer_Next_Year__Work_Dispach_For_Job,
                    @SettingsAndUtilities__Transfer_Next_Year__Job_Receive_For_Work, @SettingsAndUtilities__Transfer_Next_Year__Mill_Issue,
                    @SettingsAndUtilities__Transfer_Next_Year__Mill_Job_Receive, @SettingsAndUtilities__Transfer_Next_Year__Taka_Production,
                    @SettingsAndUtilities__Transfer_Next_Year__Box_Production, @SettingsAndUtilities__Delete_Previous_Year__Closing_Stock,
                    @SettingsAndUtilities__Delete_Previous_Year__Closing_Amount, @SettingsAndUtilities__Delete_Previous_Year__Sales_Invoice,
                    @SettingsAndUtilities__Delete_Previous_Year__Purchase_Invoice, @SettingsAndUtilities__Delete_Previous_Year__Work_Dispach_For_Job,
                    @SettingsAndUtilities__Delete_Previous_Year__Job_Receive_For_Work, @SettingsAndUtilities__Delete_Previous_Year__Mill_Issue,
                    @SettingsAndUtilities__Delete_Previous_Year__Mill_Job_Receive, @SettingsAndUtilities__Delete_Previous_Year__Taka_Production,
                    @SettingsAndUtilities__Delete_Previous_Year__Box_Production, @SettingsAndUtilities__Transport_Setting__Firm,
                    @SettingsAndUtilities__Transport_Setting__Branch, @SettingsAndUtilities__Transport_Setting__LR_Rate,
                    @SettingsAndUtilities__Transport_Setting__Contract_Rate, @SettingsAndUtilities__Transport_Setting__LR_Booking_Range,
                    GETUTCDATE(), @UserId)
            
            SET @Id = SCOPE_IDENTITY()
        END
        
        COMMIT TRAN

        SELECT @Id
    END TRY
    BEGIN CATCH
        DECLARE @error INT, @message VARCHAR(4000), @xstate INT;
        SELECT @error = ERROR_NUMBER(), @message = ERROR_MESSAGE(), @xstate = XACT_STATE();
        ROLLBACK TRAN

        IF (CHARINDEX('IX_MenuSetting', @message) > 0)
		BEGIN
			SET @message = 'Menu setting already exist!'
		END

        RAISERROR ('%s', 16, 1, @message);
    END CATCH
END
GO