using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Adroit.Accounting.Model.Enums
{
    public enum BookTypeList
    {
        [Description("Chalan")]
        Chalan,
        [Description("Sales")]
        Sales,
        [Description("SalesReturn")]
        SalesReturn,
        [Description("Purchase")]
        Purchase,
        [Description("PurchaseReturn")]
        PurchaseReturn,
        [Description("CreditNote")]
        CreditNote,
        [Description("DebiteNote")]
        DebiteNote,
        [Description("GeneralExps")]
        GeneralExps,
        [Description("Cash")]
        Cash,
        [Description("Bank")]
        Bank,
        [Description("TransportLr")]
        TransportLr,
        [Description("TransportChalan")]
        TransportChalan,
        [Description("SalesOrder")]
        SalesOrder,
        [Description("PurchaseOrder")]
        PurchaseOrder,
        [Description("ProformaInvoice")]
        ProformaInvoice,
        [Description("Quotation")]
        Quotation,
        [Description("OutsideJobIssueSelf")]
        OutsideJobIssueSelf,
        [Description("OutsideJobReceiveSelf")]
        OutsideJobReceiveSelf,
        [Description("WorkIssueManf")]
        WorkIssueManf,
        [Description("WorkReceiveManf")]
        WorkReceiveManf,
        [Description("JobworkReceive")]
        JobworkReceive,
        [Description("JobworkIssue")]
        JobworkIssue,
        [Description("GoDownIssue")]
        GoDownIssue,
        [Description("GoDownReceive")]
        GoDownReceive,
        [Description("StockIssue")]
        StockIssue,
        [Description("StockReceive")]
        StockReceive,
        [Description("bhavisha1")]
        bhavisha1,
        [Description("BHAVISHA")]
        BHAVISHA
    }
}
